apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: family-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
      metadata:
        labels:
          app: discord-bot
      spec:
        containers:
          - name: bot
            env:
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: http://grafana-k8s-monitoring-alloy-receiver.family-tree.svc.cluster.local:4317 # grpc - use 4318 for HTTP
              - name: OTEL_EXPORTER_OTLP_PROTOCOL
                value: grpc

            image: ghcr.io/anderswallace/bot:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: bot-env
