receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Debug
  debug:
    verbosity: detailed

  # Logs
  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  # Traces
  otlphttp/tempo:
    endpoint: http://tempo:4318

  # Metrics
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/loki]
    traces:
      receivers: [otlp]
      exporters: [debug, otlphttp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
