name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - "bot/src/**"
      - "bot/Dockerfile"
      - ".github/workflows/deployment.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    name: Build and Push

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bot:latest
            ghcr.io/${{ github.repository_owner }}/got:${{ github.sha }}
